import { useEffect,useState } from "react";
import { BookOpen,Save } from "lucide-react";
import { COLORS } from "../../constants/theme";
import { supabase } from "../../services/supabase";
const today=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
async function userId(name){let r=await supabase.from("users").select("id").eq("display_name",name).maybeSingle();if(!r.data&&!r.error)r=await supabase.from("users").select("id").eq("name",name).maybeSingle();if(r.error)throw r.error;return r.data?.id;}
export default function EntertainmentProgressSection({currentUser,items,onChange}){const[id,setId]=useState(null),[selected,setSelected]=useState(""),[form,setForm]=useState({page_number:"",season_number:"",episode_number:"",progress_date:today(),notes:""}),[error,setError]=useState("");useEffect(()=>{userId(currentUser).then(setId).catch(e=>setError(e.message))},[currentUser]);const item=items.find(x=>x.id===selected);async function save(e){e.preventDefault();if(!item)return setError("Escolha um livro ou série.");const progress={entertainment_item_id:item.id,registered_by_user_id:id,progress_date:form.progress_date,page_number:item.item_type==="livro"?Number(form.page_number||0):null,season_number:item.item_type==="serie"?Number(form.season_number||0):null,episode_number:item.item_type==="serie"?Number(form.episode_number||0):null,notes:form.notes.trim()||null};const{error:a}=await supabase.from("entertainment_progress").insert(progress);if(a)return setError(a.message);const update=item.item_type==="livro"?{current_page:progress.page_number,status:"em_andamento",updated_at:new Date().toISOString()}:{current_season:progress.season_number,current_episode:progress.episode_number,status:"em_andamento",updated_at:new Date().toISOString()};const{error:b}=await supabase.from("entertainment_items").update(update).eq("id",item.id);if(b)return setError(b.message);setForm({page_number:"",season_number:"",episode_number:"",progress_date:today(),notes:""});onChange?.()}
return <section style={panel}><h3 style={{margin:"0 0 12px",color:COLORS.ink,fontSize:17,display:"flex",gap:7,alignItems:"center"}}><BookOpen size={19} color={COLORS.primaryDark}/> Atualizar progresso</h3><form onSubmit={save}><div style={grid}><Field l="Livro ou série"><select value={selected} onChange={e=>setSelected(e.target.value)} style={input}><option value="">Selecione</option>{items.filter(x=>x.item_type!=="filme"&&x.status!=="concluido").map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></Field><Field l="Data"><input type="date" value={form.progress_date} onChange={e=>setForm({...form,progress_date:e.target.value})} style={input}/></Field>{item?.item_type==="livro"&&<Field l="Página atual"><input type="number" min="0" value={form.page_number} onChange={e=>setForm({...form,page_number:e.target.value})} style={input}/></Field>}{item?.item_type==="serie"&&<><Field l="Temporada"><input type="number" min="0" value={form.season_number} onChange={e=>setForm({...form,season_number:e.target.value})} style={input}/></Field><Field l="Episódio"><input type="number" min="0" value={form.episode_number} onChange={e=>setForm({...form,episode_number:e.target.value})} style={input}/></Field></>}</div><Field l="Observações"><input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} style={input}/></Field>{error&&<div style={{color:COLORS.danger,fontSize:12,margin:"8px 0"}}>{error}</div>}<button style={button}><Save size={16}/> Salvar progresso</button></form></section>}
function Field({l,children}){return <label style={{display:"grid",gap:4,color:COLORS.inkSoft,fontSize:11}}>{l}{children}</label>}const panel={background:COLORS.surface,border:`1px solid ${COLORS.border}`,borderRadius:14,padding:17},grid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,170px),1fr))",gap:9,marginBottom:9},input={width:"100%",boxSizing:"border-box",border:`1px solid ${COLORS.border}`,borderRadius:8,padding:9,background:COLORS.surface},button={display:"inline-flex",alignItems:"center",gap:6,border:0,borderRadius:8,padding:"9px 12px",background:COLORS.primary,color:"white",fontWeight:600,fontSize: 13, marginTop:10};
